// AUTH-ACTIONS
export const LOGOUT = 'LOGOUT';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const TRY_AUTHENTICATE = 'TRY_AUTHENTICATE';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// DEVICES-ACTIONS
export const FETCH_DEVICES = 'FETCH_DEVICES';
export const FETCH_DEVICES_SUCCESS = 'FETCH_DEVICES_SUCCESS';
export const FETCH_DEVICES_FAILED = 'FETCH_DEVICES_FAILED';
