export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const TRY_AUTHENTICATE = 'TRY_AUTHENTICATE';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
