//AUTH ACTION TYPES
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';
export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED';
export const LOGOUT = 'LOGOUT';

// DEVICES ACTION TYPES
export const FETCH_DEVICES = 'FETCH_DEVICES';
export const FETCH_DEVICES_SUCCESS = 'FETCH_DEVICES_SUCCESS';
export const FETCH_DEVICES_FAILED = 'FETCH_DEVICES_FAILED';


// AIR CONDITIONER ACTION TYPES
export const SUBMIT_AC_STATE = 'SUBMIT_AC_STATE';
export const SUBMIT_AC_STATE_SUCCESS = 'SUBMIT_AC_STATE_SUCCESS';
export const SUBMIT_AC_STATE_FAILED = 'SUBMIT_AC_STATE_FAILED';
