#define FIREBASE_HOST "home-control-fe934.firebaseio.com"
#define FIREBASE_AUTH "xb8aOxIGC98rd6yakBe9bPY071KcRR9A8lutj8em"

#define DEVICE_NAME "Living Room Air Conditioner"
#define DEVICE_TYPE "AC"
#define UID "v63Qpf3GRATe5Jgz8XPHmp2tU0E2"
#define DEVICE_ID "-MK3zOf-KoaDLGkBwYEr"
#define READ_AC_PATH "/-MK3zOf-KoaDLGkBwYEr/app_to_ino"
#define WRITE_AC_PATH "/-MK3zOf-KoaDLGkBwYEr/ino_to_app/ac"
#define WRITE_AC_DATE_PATH "/-MK3zOf-KoaDLGkBwYEr/ino_to_app/ac/date"
#define WRITE_SENSOR_PATH "/-MK3zOf-KoaDLGkBwYEr/ino_to_app/sensor"
#define WIFI_SSID "phone"
#define WIFI_PASSWORD "12345678"
